#
# This file contains configuration flags to customize the blog
#

# Overall site theme
theme: jekyll-theme-cayman

# Name of blog (displayed in the header and footer)
name: The Hucklepuck

# Short bio or description (displayed in the header)
description: Bound by Code

# If the blog is being hosted at a Project repository on GitHub pages
# (http://<owner>.github.io/repository-name)
# and NOT the owner's repository (http://<owner>.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# URL of blog avatar
avatar: /images/logo.png

# URL of author avatar
author_avatar: https://avatars0.githubusercontent.com/u/38449003?v=4

# URL of blog favicon (Google browser only respects this url)
favicon: https://raw.githubusercontent.com/allan-mobley-jr/hucklepuck/master/favicon.ico

# Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-158855820-1

# Blog website url
# Used for Sitemap.xml and your RSS feed
url: https://www.thehucklepuck.com

# Blog repo url
# Used for comments
repo: allan-mobley-jr/hucklepuck

permalink: /:title/

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
